version: "3.9"

services:
  app:
    build: ./
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - "${JSON_API_PORT}:${JSON_API_PORT}"
      - "${GRPC_API_PORT}:${GRPC_API_PORT}"
    command: [ "/app/main" ]
    entrypoint:
      [
        "/app/scripts/wait_for.sh",
        "${POSTGRES_HOST}:${POSTGRES_PORT}",
        "--",
        "/app/scripts/start.sh"
      ]

  postgres:
    image: postgres:15.3-alpine3.18
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:7.0-alpine3.18
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
