version: "3.9"

services:
  app:
    build: ./
    container_name: app
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
      - "9090:9090"

  postgres:
    image: postgres:15.3-alpine3.18
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis:7.0-alpine3.18
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
