name: CI

on:
  push:
    branches: [main]
    paths: ["**.go"]

  pull_request:
    branches: [main]
    paths: ["**.go"]

  workflow_dispatch:

jobs:
  test:
    services:
      postgres:
        image: postgres:15.3-alpine3.18
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Set up Just
        uses: extractions/setup-just@v1

      - name: Install migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/migrate
          which migrate

      - name: Run migrations
        run: just migrate ${{ secrets.POSTGRES_URI }} up

      - name: Run tests
        run: just test

      - name: Upload code coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          verbose: true

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
          cache: false

      - name: Run Go linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          args: --timeout=10m
